require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.tabnine"
require "user.treesitter"
require "user.vim-test"
require "user.autopairs"

