require "user.keymaps"
require "user.which-key"

require "user.alpha"
require "user.autocommands"
require "user.autopairs"
require "user.cmp"
require "user.colorscheme"
require "user.comment"
require "user.gitsigns"
require "user.impatient"
require "user.indentline"

require "user.lsp"
require "user.lualine"
require "user.neogen"
require "user.nvim-tree"
require "user.octo"
require "user.options"
require "user.plugins"
require "user.project"
require "user.tabnine"
require "user.telescope"
require "user.toggleterm"
require "user.treesitter"
require "user.vim-test"


require "user.bufferline"
